# -*- coding: utf-8 -*-
"""movieRecommendation.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1rtUG1NwR3E7_L6evx7eNaxE9MyZSSZ4M
"""

try:
  import numpy as np
  from lightfm.datasets import fetch_movielens
  from lightfm import LightFM
except:
  !pip install scipy numpy lightfm

# try to run this on collab cause in local machine vs build tool v 14 + needed
import numpy as np
from lightfm.datasets import fetch_movielens
from lightfm import LightFM

# fetch data and format it
data=fetch_movielens(min_rating=4)

# print training and testing data
print(repr(data["train"]))
print(repr(data["test"]))

# create model
model=LightFM(loss='warp')
# warp : Weighted Approximate Rank Pairwise (uses gradient descent)

# Train the model
model.fit(data["train"], epochs=30, num_threads=2)

def sample_recommendation(model,data,user_ids):

  n_users,n_items =data['train'].shape
  print(data['train'])
  # for user_id in user_ids:
  #   know_positives=data['item_labels'][data['train'].tocsr()[user_id].indices]

  #   scores=model.predict(user_id,np.arange(n_items))
  #   top_items=data['item_labels'][np.argsort(-scores)]
  #   print("User %s" % user_id)
  #   print("     Known positives:")

  #   print(know_positives[:])

sample_recommendation( model,data,[10,24,69])

